### ISSUE TITLE
Cannot build on OpenBSD 6.1

### ISSUE THREAD

**Issue by enzoh** [AndrewScheidecker/WAVM#56]
Scanning dependencies of target Platform
[  2%] Building CXX object Source/Platform/CMakeFiles/Platform.dir/POSIX.cpp.o
/home/custodian/workspace/tmp/WAVM/Source/Platform/POSIX.cpp: In function 'void Platform::initThread()':
/home/custodian/workspace/tmp/WAVM/Source/Platform/POSIX.cpp:151:64: error: 'pthread_get_stackaddr_np' was not declared in this scope
     stackMaxAddr = (U8*)pthread_get_stackaddr_np(pthread_self());
                                                                ^
/home/custodian/workspace/tmp/WAVM/Source/Platform/POSIX.cpp: In function 'void Platform::signalHandler(int, siginfo_t*, void*)':
/home/custodian/workspace/tmp/WAVM/Source/Platform/POSIX.cpp:182:40: error: comparison between distinct pointer types 'caddr_t {aka char*}' and 'U8* {aka unsigned char*}' lacks a cast [-fpermissive]
    signalType = signalInfo->si_addr >= stackMinAddr && signalInfo->si_addr < stackMaxAddr
                                        ^
/home/custodian/workspace/tmp/WAVM/Source/Platform/POSIX.cpp:182:78: error: comparison between distinct pointer types 'caddr_t {aka char*}' and 'U8* {aka unsigned char*}' lacks a cast [-fpermissive]
    signalType = signalInfo->si_addr >= stackMinAddr && signalInfo->si_addr < stackMaxAddr
                                                                              ^
*** Error 1 in . (Source/Platform/CMakeFiles/Platform.dir/build.make:63 'Source/Platform/CMakeFiles/Platform.dir/POSIX.cpp.o': cd /home/cust...)
*** Error 1 in . (CMakeFiles/Makefile2:305 'Source/Platform/CMakeFiles/Platform.dir/all')
*** Error 1 in /home/custodian/workspace/tmp/WAVM/release (Makefile:95 'all')

**Comment by AndrewScheidecker** [comment]
What compiler are you using? I installed OpenBSD 6.1 in a VM, but I'm getting other compile errors about the use of `__thread`.
